# Core
DASHBOARD = "127.0.0.1:3000"
JWT_Sercret = "LjNpCp5z9H"
Port = "8090"

# Database
DB_Host = "127.0.0.1"
DB_Name = "waf"
DB_Password = "password"
DB_Port = "5432"
DB_User = "postgres"

# Mail
EMAIL_PASSWORD = "uaoa aeyl hypd gwkc"
EMAIL_SENDER = "isophtalic@gmail.com"
MAIL_TEMPLATE_PATH = "./internal/pkg/mail/template/template.html"
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "587"
